"""
parse_questions.py
Parses JNCIA.docx into questions.json used by the Telegram bot.
Run once locally to (re)generate the question bank JSON.
"""
from docx import Document
from docx.oxml.ns import qn
import json, re, os

DOCX_PATH = os.path.join(os.path.dirname(__file__), 'JNCIA.docx')
OUT_PATH   = os.path.join(os.path.dirname(__file__), 'questions.json')
IMG_MAP_PATH = os.path.join(os.path.dirname(__file__), 'image_map.json')


OPTION_LETTERS = list('ABCDE')


def normalize_option(txt, expected_letter):
    """
    Ensure an option text starts with 'X. ' prefix.
    Handles cases like 'A static route' (missing dot) → 'B. A static route'
    when the letter doesn't match position.
    We trust position over embedded letter for options without proper prefix.
    """
    txt = txt.strip()
    prefix = expected_letter + '. '
    # Already properly prefixed with expected letter
    if txt.upper().startswith(expected_letter + '.') or txt.upper().startswith(expected_letter + ' '):
        # Normalize to "X. rest"
        return expected_letter + '. ' + txt[2:].strip()
    # Has some other letter prefix — keep as-is (parser already decided it's an option)
    return txt


def extract_questions():
    doc = Document(DOCX_PATH)
    paras = doc.paragraphs

    # Load image map (generated by extract_images.py)
    if os.path.exists(IMG_MAP_PATH):
        with open(IMG_MAP_PATH) as f:
            img_map = json.load(f)
    else:
        img_map = {}

    questions = []
    i = 0
    while i < len(paras):
        p = paras[i]
        if p.style.name == 'Heading 7' and 'Question' in p.text:
            m = re.search(r'Question\s+(\d+)', p.text)
            if not m:
                i += 1
                continue
            qnum = int(m.group(1))
            q = {
                'number': qnum,
                'body': [],
                'options': [],
                'answer': '',
                'images': img_map.get(str(qnum), []),
            }
            i += 1
            while i < len(paras):
                pp = paras[i]
                if pp.style.name == 'Heading 7' and 'Question' in pp.text:
                    break
                txt = pp.text.strip()
                if re.match(r'^Correct Answer\s*:', txt, re.IGNORECASE):
                    ans = re.sub(r'^Correct Answer\s*:\s*', '', txt, flags=re.IGNORECASE).strip()
                    q['answer'] = ans
                elif re.match(r'^[A-E][.\s]', txt) and txt:
                    q['options'].append(txt)
                elif txt and not txt.startswith('*') and txt not in ('Click the Exhibit button.',):
                    q['body'].append(txt)
                i += 1

            # ── Post-process: fix questions where options bled into body ──────
            # If no options but we have an answer, try to rescue from body
            if not q['options'] and q['answer']:
                num_opts = len(q['answer'])          # e.g. 'AC' → 4 options
                expected = len(OPTION_LETTERS[:4])   # default 4
                # Heuristic: last N body items are likely options
                # Determine how many to pull (look for option-like lines)
                rescue = []
                remaining_body = []
                for line in q['body']:
                    # A line is an option candidate if it's short-ish and doesn't end in '?'
                    if len(line) < 120 and not line.endswith('?') and len(rescue) < 4:
                        rescue.append(line)
                    else:
                        remaining_body.append(line)
                # Only apply rescue if we got a reasonable number of option candidates
                if 2 <= len(rescue) <= 5:
                    q['body'] = remaining_body
                    # Assign A/B/C/D labels
                    q['options'] = [
                        OPTION_LETTERS[idx] + '. ' + line
                        for idx, line in enumerate(rescue)
                    ]

            # ── Post-process: options missing proper A./B. prefix ─────────────
            # e.g. ['A directly connected route', 'A static route', ...]
            # Detect when option letter doesn't match its position
            normalized = []
            for idx, opt in enumerate(q['options']):
                expected_letter = OPTION_LETTERS[idx] if idx < len(OPTION_LETTERS) else '?'
                opt_letter = opt[0].upper() if opt else ''
                if opt_letter != expected_letter:
                    # Option starts with wrong letter or no letter — prefix it
                    normalized.append(expected_letter + '. ' + opt)
                else:
                    normalized.append(opt)
            q['options'] = normalized

            # ── Hardcoded fixes for known bad format in DOCX ──────────────────
            if q['number'] == 47:
                q['body'] = [
                    "You need to configure interface ge-0/1/2 with an IP address of 172.16.100.1/24.",
                    "You have accidentally entered 172.16.101.1/24 as shown in the exhibit.",
                    "Which command should you issue to solve the problem?"
                ]
                q['options'] = [
                    "A. [edit] user@route# rollback rescue",
                    "B. [edit] user@route# rollback 2",
                    "C. [edit] user@route# rollback 0",
                    "D. [edit] user@route# rollback 1"
                ]
                # It says AD in docx, but likely a typo. We leave it as AD or D, docx says AD.
                q['answer'] = "AD"

            if q['number'] == 105:
                q['body'] = ["Which two statements are true about the Junos OS (Choose two)"]
                q['options'] = [
                    "A. Routing table are stored in the control plane.",
                    "B. Exception traffic is never sent to the control plane.",
                    "C. Exception traffic is sent to the control plane.",
                    "D. Routing table are stored in the forwarding plane."
                ]
                q['answer'] = "AC"

            questions.append(q)
        else:
            i += 1

    return questions



if __name__ == '__main__':
    qs = extract_questions()
    with open(OUT_PATH, 'w', encoding='utf-8') as f:
        json.dump(qs, f, ensure_ascii=False, indent=2)
    print(f'Saved {len(qs)} questions to {OUT_PATH}')
